### PR TITLE
HelloWorld Implementation

### PR DESCRIPTION
**Pull request by naztekinalp**
HelloWorld implementation for HW1 is added.

### CODE REVIEW

**Comment by drevalanya** [comment]
1. the repository name should match the pattern FirstnameLastname - NazTekinalp
2. .idea files should be added to gitignore (as far as it is not a part of your code)
3. GitHub highlights code style issues, please, fix it
Screenshot 2023-03-13 133106

**Comment by naztekinalpp** [comment]
**the following changes have been made:**
- the repository name changed to NazTekinalp.
- .idea files added to gitignore.
- reformated code for code styling issue.

**Comment by naztekinalp** [comment]
hi @drevalanya,
**the following changes have been made:**
- the repository name changed to NazTekinalp.
- .idea files added to gitignore.
- reformated code for code styling issue.

**Comment by drevalanya** [comment]
same code style problem in gitignore
image

**Comment by naztekinalp** [comment]
Hi, I add ed new line to fix the code style problem in gitignore.

**Review by drevalanya — APPROVED** [review]

**Pull request merged**
